KarrenCupCakes/Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace KarrenCupCakes.Models
{
    public class AppUser : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }

    public class UserData
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string ConnectionId { get; set; }
    }
}

KarrenCupCakes/ViewModels/AccountViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KarrenCupCakes.ViewModels
{

    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

}

KarrenCupCakes/Controllers/AboutController.cs
using System.Web.Mvc;

namespace KarrenCupCakes.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

KarrenCupCakes/Controllers/BlogController.cs
using System.Web.Mvc;


namespace KarrenCupCakes.Controllers
{
    
    
    public class BlogController : Controller
    {
    }
}

KarrenCupCakes/Controllers/ContactController.cs
using System.Configuration;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.SignalR.Client;
using Newtonsoft.Json;
using System.Linq;
using KarrenCupCakes.Models;
using KarrenCupCakes.Core;
using System.Web;

namespace KarrenCupCakes.Controllers
{
    public class ContactController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Connect(string name, string email, string number)
        {
            UserData userData = new UserData();
            userData.Name = name;
            userData.Email = email;
            userData.Phone = number;

            Session.Add("UserData", userData);

            bool result = SignalRConnector.AddThisUser(userData);

            return Json(result);
        }

        public ActionResult SendMessage(string message)
        {
            UserData userData = (UserData)Session["UserData"];

            bool result = SignalRConnector.SendMessage(userData, message);

            return Json(result);
        }

        public static void MessageReceived(string message)
        {
            
        }
	}
}

KarrenCupCakes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KarrenCupCakes.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

KarrenCupCakes/Controllers/OtherController.cs
using System.Web.Mvc;


namespace KarrenCupCakes.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult FullWidth()
        {
            return View();
        }
        
        public ActionResult SideBar()
        {
            return View();
        }
        
        public ActionResult FourOhFour()
        {
            return View();
        }
    }
}

KarrenCupCakes/Controllers/PortfolioController.cs
using System.Web.Mvc;


namespace KarrenCupCakes.Controllers
{
    
    
    public class PortfolioController : Controller
    {
        
        public ActionResult Cakes()
        {
            return View(); 
        }

        public ActionResult Desserts()
        {
            return View();
        }

        public ActionResult Pasta()
        {
            return View();
        }
    }
}

KarrenCupCakes/Controllers/ServicesController.cs
using System.Web.Mvc;

namespace KarrenCupCakes.Controllers
{
    public class ServicesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

KarrenCupCakes/Views/About/Index.cshtml
@{
    ViewBag.Title = "About";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Welcome to my page! 
                <small>It's Nice to Meet You!</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
            </li>
            <li class="active">About</li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <img src="http://placehold.it/750x450" class="img-responsive">
    </div>
    <div class="col-md-6">
        <h2>Karren's Pastry Caf&eacute;</h2>
        <p></p>
        <p></p>
    </div>
</div>
<!-- Team Member Profiles -->
@*<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Our Team</h2>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
</div>*@
<!-- Our Customers -->
@*<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Our Customers</h2>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
</div>*@
</div>

KarrenCupCakes/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Contact";
}

<script src="http://hubserver.apphb.com/Scripts/jquery-2.2.0.js"></script>
<script src="http://hubserver.apphb.com/Scripts/jquery.signalR-2.2.0.js"></script>
<script src="http://hubserver.apphb.com/signalr/hubs"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#chatHead').show();
        $('#chatBox').hide();
    });

    $(function () {

        $.connection.hub.url = 'http://hubserver.apphb.com/signalr';
        var hub = $.connection.chatterHub;

        $.connection.hub.start()
            .done(function () { console.log('Now connected, connectionID = ' + $.connection.hub.id); })
            .fail(function () { console.log('Could not connect!!'); });

        $('#connect').click(function () {
            var xname = $('#input1').val();
            var xemail = $('#input2').val();
            var xnumber = $('#input3').val();

            if (xname == '' && xemail == '' && xnumber == '') {
                alert('Please fill up the name, address and email! Thank you!');
            }
            else {
                $('#chatHead').hide();
                $('#chatBox').show();
            };
        });
    });
</script>

@*<script type="text/javascript">
    $(document).ready(function () {
    $('#connect').click(function () {
        var xname = $('#input1').val();
        var xemail = $('#input2').val();
        var xnumber = $('#input3').val();

        $.ajax({
            url: "@(Url.Action("Connect", "Contact"))",
            type: "POST",
            data: { name: xname, email: xemail, number: xnumber },
            cache: false,
            async: true,
            success: function (data) {
                if (data)
                {
                    $('#divChat').append('<li><strong>' + xname + '</strong>:&nbsp;&nbsp; you are now connected!</li>');
                    //console.log(data);
                    //$('#input5').val(xname + ": you are now connected!");
                }
            }
        });
    });

    $('#send').click(function () {
        var xname = $('#input1').val();
        var xemail = $('#input2').val();
        var xnumber = $('#input3').val();

        $.ajax({
            url: "@(Url.Action("Connect", "Contact"))",
            type: "POST",
        data: { name: xname, email: xemail, number: xnumber },
        cache: false,
        async: true,
        success: function (data) {
            if (data)
            {
                var xmessage = $('#input4').val();
                var xname = $('#input1').val();

                $.ajax({
                    url: "@(Url.Action("SendMessage", "Contact"))",
                    type: "POST",
                data: { message: xmessage },
                cache: false,
                async: true,
                success: function (data) {
                        if(data)
                        {
                            console.log(data);
                            $('#divChat').append('<li><strong>' + xname + '</strong>:&nbsp;&nbsp;' + xmessage + '</li>');
                            $('#divChat').append('<li><strong>' + xname + '</strong>:&nbsp;&nbsp;message sent!</li>');
                        }
                    }
                });
                //$('#divChat').append('<li><strong>' + xname + '</strong>:&nbsp;&nbsp; you are now connected!</li>');
                //console.log(data);
                //$('#input5').val(xname + ": you are now connected!");
            }
        }
        });
    });
</script>*@

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Contact <small>We'd Love to Hear From You!</small></h1>
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="active">Contact</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <h3>Let's Get In Touch!</h3>
            <p>If you have some inquiries, questions or concerns, you may directly send a message to Karren's Pastry Cafe below and we'll send you an email or text you regarding your question or concern.</p>

            <div id="chatHead" class="row">
                <div class="form-group col-lg-4">
                    <label for="input1">Name</label>
                    <input type="text" id="input1" class="form-control" name="name" />
                    <label for="input2">Email Address</label>
                    <input type="email" id="input2" class="form-control" name="email" />
                    <label for="input3">Phone Number</label>
                    <input type="number" id="input3" class="form-control" name="number" />
                    <br/>
                    <button class="btn btn-primary" id="connect" type="submit" style="float: right;">Connect</button>
                </div>
            </div>

            <div id="chatBox" class="row">
                <div class="form-group col-lg-12">
                    <label for="sendMsg">Type message here:</label>
                    <input type="text" id="sendMsg" class="form-control" name="msg" />
                    <br />
                    <button class="btn btn-primary" id="send" type="submit" style="float: right;">Send</button>
                </div>

                <div class="form-group col-lg-12">
                    <label for="input4">Messages</label>
                    <textarea rows="20" type="text" id="input4" class="form-control" name="contact_message"></textarea>
                </div>
            </div>
        </div>
    </div>
</div>

KarrenCupCakes/Views/Other/FourOhFour.cshtml
@{
    ViewBag.Title = "FAQ";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                404
                <small>Page Not Found</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">404</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p class="error-404">404</p>
            <p class="lead">The page you're looking for could not be found.</p>
            <p>Here are some helpful links to help you find what you're looking for:</p>
            <ul>
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
                <li>
                    <a href="#">Blog</a>
                </li>
                <li>
                    <a href="#">Other</a>
                </li>
            </ul>
        </div>
    </div>
</div>

KarrenCupCakes/Views/Other/FullWidth.cshtml
@{
    ViewBag.Title = "Full Width Page";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Full Width Page
                <small>For Deeper Customization</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Full Width Page</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p>This page features a page header, breadcrumbs, and the footer but that's it. Use this as a template for completely custom pages you wish to add to your site.</p>
            <p>Be sure to read over and understand all of the Bootstrap 3 components at <a href="http://getbootstrap.com">http://getbootstrap.com</a> to get the most out of any Start Bootstrap template.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam placerat nunc ut tellus tristique, non posuere neque iaculis. Fusce aliquet dui ut felis rhoncus, vitae molestie mauris auctor. Donec pellentesque feugiat leo a adipiscing. Pellentesque quis tristique eros, sed rutrum mauris.</p>
        </div>
    </div>
</div>

KarrenCupCakes/Views/Portfolio/Cakes.cshtml
@{
    ViewBag.Title = "Cake and Cupcake";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Cakes and Cupcakes
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Cakes and Cupcakes</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">All Related Cake and Cupcake Orders</h3>
        </div>
        @for (int i = 1; i < 21; i++)
        {
            <div class="col-sm-3 col-xs-6">
                <img src="@Url.Content(string.Format("~/Images/Cakes/cakes_{0}.jpg", i))" class="img-responsive img-customer">
            </div>
        }
    </div>
    <div class="row well">
        <div class="col-lg-8 col-md-8">
            <h4>More cakes and cupcakes pictures and designs on our facebook page.</h4>
            <p>Check it out by clicking this link <a href="https://www.facebook.com/pg/karrencupcakes/photos/">here</a>.</p>
        </div>
    </div>
</div>

KarrenCupCakes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Karren's Pastry Caf&eacute;</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">
    <link href="@Url.Content("/css/font-awesome.css")" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                @Html.ActionLink("Karren's Pastry Café", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    @*<li id="about">
                        @Html.ActionLink(" About", "Index", "About", null, new { @class = "fa fa-question-circle fa-lg" })
                    </li>*@
                    @*<li id="services">
                        @Html.ActionLink("Services", "Index", "Services")
                    </li>*@
                    <li id="contact">
                        @Html.ActionLink(" Contact", "Index", "Contact", null, new { @class = "fa fa-phone-square fa-lg" })
                    </li>
                    <li id="portfolio" class="dropdown">
                        <a href="#" class="dropdown-toggle fa fa-info-circle fa-lg" data-toggle="dropdown"> Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="cakeandcupcakeitem">
                                @Html.ActionLink("Cakes", "Cakes", "Portfolio")
                            </li>
                            <li id="cakeandcupcakeitem">
                                @Html.ActionLink("Desserts", "Desserts", "Portfolio")
                            </li>
                            <li id="cakeandcupcakeitem">
                                @Html.ActionLink("Pasta", "Pasta", "Portfolio")
                            </li>
                        </ul>
                    </li>
                    
                    @*<li id="other" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="fullwidthpage">
                                @Html.ActionLink("Full Width Page", "FullWidth", "Other")
                            </li>
                            <li id="sidebarpage">
                                @Html.ActionLink("Sidebar Page", "Sidebar", "Other")
                            </li>
                            
                            <li id="404">
                                @Html.ActionLink("404", "FourOhFour", "Other")
                            </li>
                            
                        </ul>
                    </li>*@
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    <div class="container">
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-9 text-info">
                    <h3>Karren's Pastry Caf&eacute;</h3>
                    <p>
                        LJjG Condo Homes, Bihagville<br>
                        Sto. Niño I, Casili, Consolacion, 6001<br>
                    </p>
                </div>
                <div class="col-lg-9 text-info">
                    <p><i class="fa fa-phone"></i><abbr title="Phone">P</abbr>: (956) 286-2686</p>
                    <p><i class="fa fa-envelope-o"></i><abbr title="Email">E</abbr>: <a href="mailto:karrenspastrycafe@outlook.com">karrenspastrycafe@outlook.com</a></p>
                    
                    <ul class="list-unstyled list-inline list-social-icons" style="vertical-align: middle">
                        <li class="tooltip-social facebook-link"><a title="Facebook" data-placement="top" data-toggle="tooltip" href="https://www.facebook.com/karrencupcakes/"><i class="fa fa-facebook-square fa-2x"></i></a></li>
                        <li><i class="fa fa-copyright fa-lg" aria-hidden="true" style="vertical-align: middle"> Karren's Pastry Cafe 2017 </i></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->

    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>*@
    <script src="@Url.Content("/js/bootstrap.js")"></script>
    @*<script src="@Url.Content("/js/modern-business.js")"></script>*@
</body>
</html>